/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 house.gltf
Author: ModelMaker (https://sketchfab.com/mireubay1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/game-ready-city-building-2bd7122c0f774cb48565187848154436
Title: Game Ready City Building
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function House(props) {
  const { nodes, materials } = useGLTF("/house.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.atlas}
        position={[-1.47, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.atlas}
        position={[-1.47, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.atlas}
        position={[-0.92, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.atlas}
        position={[-1.1, -0.2, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.38}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.atlas}
        position={[-0.36, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.atlas}
        position={[-0.36, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.atlas}
        position={[0.19, -0.22, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.atlas}
        position={[0.02, -0.2, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.38}
      />
      <mesh
        geometry={nodes.Object_20.geometry}
        material={materials.atlas}
        position={[-1.43, 0.16, 0.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_22.geometry}
        material={materials.atlas}
        position={[-1.76, -0.33, 0.04]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_24.geometry}
        material={materials.atlas}
        position={[-1.19, -0.33, 0.04]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.atlas}
        position={[-0.62, -0.33, 0.04]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.atlas}
        position={[-0.08, -0.33, 0.04]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.atlas}
        position={[0.51, -0.33, 0.04]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_32.geometry}
        material={materials.atlas}
        position={[-0.61, 0.34, -0.92]}
      />
      <mesh
        geometry={nodes.Object_34.geometry}
        material={materials.atlas}
        position={[-1.48, 0.63, 0.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.64}
      />
      <mesh
        geometry={nodes.Object_36.geometry}
        material={materials.atlas}
        position={[-1.46, 2.22, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.05}
      />
      <mesh
        geometry={nodes.Object_38.geometry}
        material={materials.atlas}
        position={[-0.58, 2.01, -0.92]}
      />
      <mesh
        geometry={nodes.Object_40.geometry}
        material={materials.atlas}
        position={[-1.77, -0.22, -2]}
        rotation={[Math.PI / 2, 0, 1.57]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.atlas}
        position={[-1.77, -0.22, -1.45]}
        rotation={[Math.PI / 2, 0, 1.57]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.atlas}
        position={[-1.77, -0.22, -0.88]}
        rotation={[Math.PI / 2, 0, 1.57]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.atlas}
        position={[-1.77, -0.22, -0.34]}
        rotation={[Math.PI / 2, 0, 1.57]}
      />
      <mesh
        geometry={nodes.Object_48.geometry}
        material={materials.atlas}
        position={[-1.79, 0.16, -1.96]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_50.geometry}
        material={materials.atlas}
        position={[-1.8, -0.33, -2.28]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_52.geometry}
        material={materials.atlas}
        position={[-1.8, -0.33, -1.72]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_54.geometry}
        material={materials.atlas}
        position={[-1.8, -0.33, -1.15]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_56.geometry}
        material={materials.atlas}
        position={[-1.8, -0.33, -0.61]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.atlas}
        position={[-1.8, -0.33, -0.01]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.atlas}
        position={[-1.79, -0.23, -1.96]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.atlas}
        position={[0.53, -0.22, -0.3]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.atlas}
        position={[0.53, -0.22, -0.84]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_66.geometry}
        material={materials.atlas}
        position={[0.53, -0.22, -1.41]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_68.geometry}
        material={materials.atlas}
        position={[0.53, -0.22, -1.96]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Object_70.geometry}
        material={materials.atlas}
        position={[0.56, 0.16, -0.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_72.geometry}
        material={materials.atlas}
        position={[0.56, -0.33, -0.01]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_74.geometry}
        material={materials.atlas}
        position={[0.56, -0.33, -0.58]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_76.geometry}
        material={materials.atlas}
        position={[0.56, -0.33, -1.14]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_78.geometry}
        material={materials.atlas}
        position={[0.56, -0.33, -1.69]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_80.geometry}
        material={materials.atlas}
        position={[0.56, -0.33, -2.28]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_82.geometry}
        material={materials.atlas}
        position={[0.55, -0.23, -0.34]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_84.geometry}
        material={materials.atlas}
        position={[0.22, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_86.geometry}
        material={materials.atlas}
        position={[0.22, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_88.geometry}
        material={materials.atlas}
        position={[-0.32, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_90.geometry}
        material={materials.atlas}
        position={[-0.15, -0.2, -2.31]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.38}
      />
      <mesh
        geometry={nodes.Object_92.geometry}
        material={materials.atlas}
        position={[-0.89, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_94.geometry}
        material={materials.atlas}
        position={[-0.89, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_96.geometry}
        material={materials.atlas}
        position={[-1.44, -0.22, -2.28]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Object_98.geometry}
        material={materials.atlas}
        position={[-1.26, -0.2, -2.31]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.38}
      />
      <mesh
        geometry={nodes.Object_100.geometry}
        material={materials.atlas}
        position={[0.18, 0.16, -2.31]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.73}
      />
      <mesh
        geometry={nodes.Object_102.geometry}
        material={materials.atlas}
        position={[0.51, -0.33, -2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_104.geometry}
        material={materials.atlas}
        position={[-0.06, -0.33, -2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_106.geometry}
        material={materials.atlas}
        position={[-0.62, -0.33, -2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_108.geometry}
        material={materials.atlas}
        position={[-1.17, -0.33, -2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_110.geometry}
        material={materials.atlas}
        position={[-1.76, -0.33, -2.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_112.geometry}
        material={materials.atlas}
        position={[0.52, 2.22, -0.29]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.05}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.atlas}
        position={[0.24, 2.22, -2.27]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={1.05}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials.atlas}
        position={[-1.74, 2.22, -1.99]}
        rotation={[Math.PI / 2, 0, 1.57]}
        scale={1.05}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials.atlas}
        position={[-0.58, 2.36, -0.92]}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials.atlas}
        position={[0.5, 1.74, -0.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_122.geometry}
        material={materials.atlas}
        position={[-0.04, 1.74, -0.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_124.geometry}
        material={materials.atlas}
        position={[-0.61, 1.74, -0.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_126.geometry}
        material={materials.atlas}
        position={[-1.18, 1.74, -0.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_128.geometry}
        material={materials.atlas}
        position={[-1.71, 1.74, -0.02]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_130.geometry}
        material={materials.atlas}
        position={[0.5, 1.74, -2.24]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_132.geometry}
        material={materials.atlas}
        position={[-0.04, 1.74, -2.24]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_134.geometry}
        material={materials.atlas}
        position={[-0.61, 1.74, -2.24]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_136.geometry}
        material={materials.atlas}
        position={[-1.18, 1.74, -2.24]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_138.geometry}
        material={materials.atlas}
        position={[-1.71, 1.74, -2.24]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_140.geometry}
        material={materials.atlas}
        position={[0.5, 1.74, -1.7]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.atlas}
        position={[-1.71, 1.74, -1.7]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials.atlas}
        position={[0.5, 1.74, -1.13]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials.atlas}
        position={[-1.71, 1.74, -1.13]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_148.geometry}
        material={materials.atlas}
        position={[0.5, 1.74, -0.57]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_150.geometry}
        material={materials.atlas}
        position={[-1.71, 1.74, -0.57]}
        scale={0.07}
      />
      <mesh
        geometry={nodes.Object_152.geometry}
        material={materials.atlas}
        position={[-0.91, -0.09, 0.24]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Object_154.geometry}
        material={materials.atlas}
        position={[-0.34, -0.09, 0.24]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Object_156.geometry}
        material={materials.atlas}
        position={[0.21, -0.09, 0.24]}
        scale={0.19}
      />
      <mesh
        geometry={nodes.Object_158.geometry}
        material={materials.atlas}
        position={[0.48, 0.63, -0.31]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.64}
      />
      <mesh
        geometry={nodes.Object_160.geometry}
        material={materials.atlas}
        position={[0.07, 0.63, -2.24]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.64}
      />
      <mesh
        geometry={nodes.Object_162.geometry}
        material={materials.atlas}
        position={[-1.89, 0.63, -1.9]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.64}
      />
    </group>
  );
}

useGLTF.preload("/house.gltf");
