export const users = [
  {
    name: "Aarav",
    location: "Mumbai",
    rent: 30000,
    gender: "Male",
    match_percentage: 87,
    accommodation: "Flat",
  },
  {
    name: "Aditi",
    location: "Delhi",
    rent: 20000,
    gender: "Female",
    match_percentage: 56,
    accommodation: "PG",
  },
  {
    name: "Bhuvan",
    location: "Bangalore",
    rent: 25000,
    gender: "Male",
    match_percentage: 78,
    accommodation: "Flat",
  },
  {
    name: "Chetna",
    location: "Chennai",
    rent: 18000,
    gender: "Female",
    match_percentage: 69,
    accommodation: "Need Flat",
  },
  {
    name: "Dev",
    location: "Hyderabad",
    rent: 22000,
    gender: "Male",
    match_percentage: 81,
    accommodation: "Flat",
  },
  {
    name: "Esha",
    location: "Kolkata",
    rent: 15000,
    gender: "Female",
    match_percentage: 46,
    accommodation: "Need Flat",
  },
];
